packages:
  - packages/*
catalog:
  '@antfu/eslint-config': ^5.2.1
  bumpp: ^10.2.3
  eslint: ^9.34.0
  tsdown: ^0.14.2
  typescript: ^5.9.2
  vite: ^7.1.4
catalogs:
  integrations:
    entities: ^6.0.1
    linkify-it: ^5.0.0
    mdurl: ^2.0.0
    punycode.js: ^2.3.1
    uc.micro: ^2.1.0
  tests:
    js-yaml: ^4.1.0
    shiki: ^3.12.1
    tinyglobby: ^0.2.14
    vitest: ^3.2.4
  types:
    '@types/js-yaml': ^4.0.9
    '@types/linkify-it': ^5.0.0
    '@types/mdurl': ^2.0.0
    '@types/node': ^22.18.0
